### ISSUE TITLE
error : Repository not found

### ISSUE THREAD

**Issue by danwise91** [learn-co-curriculum/say-hello-ruby#10]
I have finished the lab and all tests are now passing. However when ever I try to push the file to github I keep on getting the following error: 

ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I do not know how to fix this error and this is the first time to receive it. Please help.

**Comment by AnnJohn** [comment]
@danwise91 sorry for the issue you're having

@kvignali could your team look into the above issue ^^. thanks

**Comment by kvignali** [comment]
@danwise91 are you still seeing this issue?

**Comment by danwise91** [comment]
Hello sorry for the late response. Yes I am still seeing this error it is
not allowing me to push the lab.
Daniel
