### ISSUE TITLE
Default Arguments

### ISSUE THREAD

**Issue by Rami97** [learn-co-curriculum/say-hello-ruby#13]
Hi!

I'm in session "Default Arguments" right now and I'm trying to solve the lab task.
The code of my program I wrote in say_hello.rb is:

def say_hello(name = "Ruby programmer")
  puts "Hello #{name}!"
end
say_hello

When I run it without any arguments, it tells me:

Hello Ruby programmer!

However, everytime I run `Learn´, I get this message:

Failed examples:                                                                                                                                                  rspec ./spec/say_hello_spec.rb:10 # say_hello defaults to Ruby Programmer when no name is passed in

I can't see any mistakes, do you noticed anything wrong in my code?
I definitely saved my changes.

**Comment by AnnJohn** [comment]
Hi @Rami97 sorry for the delay with this. If you're still having issues with the lab, please use the Ask a Question tool and someone will help you with this right away. Thanks!
