### ISSUE TITLE
Invalid Beyond Current Lesson warning

### ISSUE THREAD

**Issue by alyssabhogan** [learn-co-curriculum/say-hello-ruby#16]
When forking this lesson to the Learn IDE I am alerted that it is beyond my current lesson and asked if I want to continue, but it is the lesson I am currently on (all previous lessons have been completed). I do not know if this is only happening in my case, or for all users.

**WARNING: You are attempting to open a lesson that is beyond your current lesson.
Are you sure you want to continue? [Yn]:**

<img width="363" alt="screen shot 2017-03-07 at 7 10 34 pm" src="https://cloud.githubusercontent.com/assets/10181568/23683945/c92a454e-0369-11e7-816d-6dc5f275d6a7.png">

**Comment by Joll59** [comment]
Thank you for your patience.
@alyssabhogan this looks like a bug with your IDE setup, if the issue persists please email support@flatironschool.com or refer to our help center here: http://help.learn.co/the-learn-ide. 

Closing issue for now!
