### ISSUE TITLE
Receiving a warning when I try to fork this lesson

### ISSUE THREAD

**Issue by CodeDad70** [learn-co-curriculum/say-hello-ruby#17]
I just finished the Default Arguments lesson and moved on to this one - Say Hello
When I try to open it in my IDE I receive this warning 
WARNING: You are attempting to open a lesson that is beyond your current lesson. 

All lessons are marked finished under my Curriculum tab up to this one .

**Comment by cjbrock** [comment]
Hi @CodeDad70! This warning pops up when you have a lesson that you have not completed, including the video lectures. Sometimes it also pops up when Learn and Github get a little backed up, so progress is not synced in real time. Usually if that is the case, it will clear up by the next day. If this is still happening, please contact our Technical Coaches using the Ask A Question button, and they can work with you to help you figure it out. 
Thank you! 
--Corinna
