### ISSUE TITLE
IDE gave the "you're doing a lesson ahead" warning

### ISSUE THREAD

**Issue by pmknyc** [learn-co-curriculum/say-hello-ruby#19]
FYI:
In both the local IDE and browser IDE, before forking the lesson, the IDE gave the warning that I was doing a lesson ahead of where I am in the curriculum. But that's incorrect. I had completed prior lessons.

**Comment by cjbrock** [comment]
Hi @pmknyc! This error should only be triggered if you haven't completed a lesson previously. This could also happen if you had completed a lesson, but the lights hadn't triggered properly. If this happens, pop over to Ask a Question and one of the Technical Coaches should be able to assist you.

Thank you for letting us know!
// <3 Corinna
